In [2]:
import numpy as np
import pandas as pd
from pandas import Series
from pandas import DataFrame

# 数据处理与运算

## 重新索引reindex

### Series

In [5]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [6]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [7]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [3]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [4]:
# 向前插值,index要是升序的数值

obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

### DataFrame

#### 重新索引行

In [5]:
frame = DataFrame(np.arange(9).reshape(3, 3), 
                  index = ['a', 'c', 'd'], 
                  columns = ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [13]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

#### 重新索引列

In [6]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

#### 同时重新索引行和列

In [20]:
frame.reindex(index=['a', 'b', 'c', 'd'],  columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### loc的标签索引功能

In [10]:
frame.loc[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

## 丢弃数据drop

### Series

In [13]:
obj = Series(np.arange(5), index=['a','b','c','d','e'])
new_obj = obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [14]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [15]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int64

### DataFrame

In [18]:
data = DataFrame(np.arange(16).reshape((4,4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [21]:
# 丢弃行

data.drop(['Ohio', 'Colorado'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [22]:
# 丢弃列

data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## 索引、选取、过滤

### Series

In [23]:
obj = Series(np.arange(4), index=['a','b','c','d'])
obj

a    0
b    1
c    2
d    3
dtype: int64

In [30]:
# 通过标签索引

obj['b']

1

In [29]:
obj[['b','a', 'd']]

b    1
a    0
d    3
dtype: int64

In [38]:
# 标签切片与普通python切片运算不同

obj['b':'c']

b    1
c    2
dtype: int64

In [31]:
# 通过值索引

obj[1]

1

In [28]:
obj[2:4]

c    2
d    3
dtype: int64

In [34]:
obj[[1,3]]

b    1
d    3
dtype: int64

In [35]:
# 通过布尔值索引

obj[obj<2]

a    0
b    1
dtype: int64

In [40]:
# 通过索引更改dataframe中数值

obj['b':'c'] = 5
obj

a    0
b    5
c    5
d    3
dtype: int64

### DataFrame

In [51]:
data = DataFrame(np.arange(16).reshape((4,4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### 列索引
通过标签索引

In [43]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [44]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

#### 行索引
通过值索引

In [45]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [47]:
# 布尔型索引

data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### 布尔型DataFrame索引

In [48]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [50]:
data[data<5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### loc
标签索引

In [58]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [52]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [57]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

#### iloc
序号值索引

In [53]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [54]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [55]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [56]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

## 算数运算

### Series

In [59]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [60]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [61]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

### DataFrame

In [62]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [63]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [64]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### 在算术方法中填充值

In [65]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [66]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [67]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [69]:
# 使用DataFrame的add方法，通过fill_value参数填充缺失值

df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [70]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [71]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [74]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame & Series

In [81]:
# 具有启发性的例子，这样的运算成为广播，DataFrame & Series的运算跟这个差不多

arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [79]:
arr[0]

array([0., 1., 2., 3.])

In [80]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [82]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [83]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [84]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [85]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [86]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [87]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [90]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 函数应用和映射
apply 用在dataframe上，用于对row或者column进行计算；

applymap 用于dataframe上，是元素级别的操作；

map （其实是python自带的）用于series上，是元素级别的操作。

In [3]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.034342 -1.274233  0.558268
Ohio    2.073693  0.210126 -0.472440
Texas   0.922653 -0.275248 -0.363936
Oregon -0.625123  2.206471 -1.289869

In [16]:
# numpy元素级数组方法

np.abs(frame)

b         d         e
Utah    0.034342  1.274233  0.558268
Ohio    2.073693  0.210126  0.472440
Texas   0.922653  0.275248  0.363936
Oregon  0.625123  2.206471  1.289869

### 例1

In [22]:
# apply 用在dataframe上，用于对row或者column进行计算

f = lambda x: x.max() - x.min()

frame.apply(f)

b    2.698816
d    3.480704
e    1.848137
dtype: float64

In [8]:
frame.apply(f, axis='columns')

Utah      1.832501
Ohio      2.546133
Texas     1.286589
Oregon    3.496340
dtype: float64

### 例2

In [15]:
#两个等价

def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

f = lambda x: Series([x.max(), x.min()], index=['max', 'min'])
frame.apply(f)

b         d         e
max  2.073693  2.206471  0.558268
min -0.625123 -1.274233 -1.289869

### 例3

In [19]:
# applymap 用于dataframe上，是元素级别的操作

format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.03  -1.27   0.56
Ohio     2.07   0.21  -0.47
Texas    0.92  -0.28  -0.36
Oregon  -0.63   2.21  -1.29

In [21]:
# map （其实是python自带的）用于series上，是元素级别的操作

frame['e'].map(format)

Utah       0.56
Ohio      -0.47
Texas     -0.36
Oregon    -1.29
Name: e, dtype: object

## 排序和排名

### 对行或列的索引进行排序
sort_index

#### Series

In [23]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [25]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

#### DataFrame

In [27]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [28]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [29]:
frame.sort_index(axis='columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [31]:
frame.sort_index(axis='columns', ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

### 对行或列的值进行排序
sort_values

#### Series

In [33]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [35]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

#### DataFrame

In [36]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [37]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [38]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

### 排名
rank()

#### Series

In [39]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [40]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [41]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

#### DataFrame

In [43]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [44]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## 带有重复值的轴索引

# 汇总和计算描述统计

# 处理缺失数据

# 层次化索引

# 其他